### ISSUE TITLE
Notifications Module

### ISSUE THREAD

**Issue by tanseercena** [tanseercena/epub-manager#9]
Notifications Module contain two parts:

1. Email Notifications:
Email notifications will be sent at specific events like epub status changed to **File Required** etc.

2. Internal Application Notifications.
It will be same as Email but does not sent email and only show notification within Application on top bar notification area.

**Comment by vwtanseer** [comment]
@faizadev  
Use https://github.com/PHPMailer/PHPMailer Library to implement Email Notifications.
Internal Application Notifications will be store against each user in database in notifications table.

Create Notifications folder in classes and then create these classes:
- Notification => Abstract class so add common methods here and one abstract method **send**
- EmailNotification => it will extends Notification class and must implement send method
- AppNotification => it will extends Notification class and must implement send method
